
# Avoid use_frameworks! declaration in your Podfile

platform :ios, '11.0'

target 'Segment-WebEngage_Example' do
use_frameworks!
  pod 'Segment-WebEngage', :path => '../'

  target 'Segment-WebEngage_Tests' do
    inherit! :search_paths
    pod 'Expecta'
    pod 'OCMock'
  end
end
