#use_frameworks!
source 'https://github.com/WebEngage/podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Segment-WebEngage_Example' do
  pod 'Segment-WebEngage', :path => '../'
  pod 'WebEngage'

  target 'Segment-WebEngage_Tests' do
    inherit! :search_paths
    pod 'Expecta', '~> 1.0'   # expecta matchers
    pod 'OCMock', '~> 3.2'   # OCMock
    
  end
end
